services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
